name: thisismasha
favicon: null
layout_spectrum: 0.5856954269111156
typography_spectrum: 0.4281201015692204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.12413873989135027
  lightness: 0.3514226593542844
  saturation: 0.34793615341186523
  rhythmicContrast: 0.8394709015265107
purpose: []
